/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.raphaelborborema.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MobilePhone service. Represents a row in the &quot;models_MobilePhone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.raphaelborborema.model.impl.MobilePhoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.raphaelborborema.model.impl.MobilePhoneImpl}.
 * </p>
 *
 * @author raphaelborborema
 * @see MobilePhone
 * @see com.raphaelborborema.model.impl.MobilePhoneImpl
 * @see com.raphaelborborema.model.impl.MobilePhoneModelImpl
 * @generated
 */
public interface MobilePhoneModel extends BaseModel<MobilePhone> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mobile phone model instance should use the {@link MobilePhone} interface instead.
	 */

	/**
	 * Returns the primary key of this mobile phone.
	 *
	 * @return the primary key of this mobile phone
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mobile phone.
	 *
	 * @param primaryKey the primary key of this mobile phone
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mobile phone.
	 *
	 * @return the ID of this mobile phone
	 */
	public long getId();

	/**
	 * Sets the ID of this mobile phone.
	 *
	 * @param id the ID of this mobile phone
	 */
	public void setId(long id);

	/**
	 * Returns the name of this mobile phone.
	 *
	 * @return the name of this mobile phone
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this mobile phone.
	 *
	 * @param name the name of this mobile phone
	 */
	public void setName(String name);

	/**
	 * Returns the brand of this mobile phone.
	 *
	 * @return the brand of this mobile phone
	 */
	@AutoEscape
	public String getBrand();

	/**
	 * Sets the brand of this mobile phone.
	 *
	 * @param brand the brand of this mobile phone
	 */
	public void setBrand(String brand);

	/**
	 * Returns the description of this mobile phone.
	 *
	 * @return the description of this mobile phone
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this mobile phone.
	 *
	 * @param description the description of this mobile phone
	 */
	public void setDescription(String description);

	/**
	 * Returns the release date of this mobile phone.
	 *
	 * @return the release date of this mobile phone
	 */
	public Date getReleaseDate();

	/**
	 * Sets the release date of this mobile phone.
	 *
	 * @param releaseDate the release date of this mobile phone
	 */
	public void setReleaseDate(Date releaseDate);

	/**
	 * Returns the price of this mobile phone.
	 *
	 * @return the price of this mobile phone
	 */
	public double getPrice();

	/**
	 * Sets the price of this mobile phone.
	 *
	 * @param price the price of this mobile phone
	 */
	public void setPrice(double price);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MobilePhone mobilePhone);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MobilePhone> toCacheModel();

	@Override
	public MobilePhone toEscapedModel();

	@Override
	public MobilePhone toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}